---
name: Build

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  haskell:
    strategy:
      matrix:
        os:
          - macos-13      # x86_64-darwin
          - macos-latest  # aarch64-darwin
          - ubuntu-latest # x86_64-linux
      fail-fast: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      # TODO: improve with matrix
      - name: Compile code ghc8107
        run: nix build .#test-ghc8107
      - name: Run tests ghc8107
        run: nix run .#test-ghc8107
      - name: Compile code ghc902
        run: nix build .#test-ghc902
      - name: Run tests ghc902
        run: nix run .#test-ghc902

  docker:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      push: false
